### ISSUE TITLE
Allow Separate Execution Parameters for Each Managed Application

### ISSUE THREAD

**Issue by emmanuelgonz** [code-lab-org/nost-tools#76]
# Description
Currently, execution parameters defined in the YAML section `execution.managed_application` are shared across all applications within an execution. This limitation restricts the flexibility needed for different applications to operate under distinct execution parameters.

## Current Configuration
```yaml
execution:
  managed_application:
    time_scale_factor: 24 # 1 simulation day = 60 wallclock minutes
    time_step: "0:00:01" # 1 second * time scale factor
    set_offset: True
    time_status_step: "0:00:10" # 10 seconds * time scale factor
    time_status_init: "2019-03-01T23:59:59+00:00"
    shut_down_when_terminated: True
    manager_app_name: "manager"

```

## Proposed Configuration

To enhance flexibility, it is necessary to define execution parameters for each application separately. For example:

```yaml
execution:
  managed_applications:
    planner:
      time_scale_factor: 24 # 1 simulation day = 60 wallclock minutes
      time_step: "0:00:01" # 1 second * time scale factor
      set_offset: True
      time_status_step: "0:00:10" # 10 seconds * time scale factor
      time_status_init: "2019-03-01T23:59:59+00:00"
      shut_down_when_terminated: True
      manager_app_name: "manager"
    appender:
      time_scale_factor: 24 # 1 simulation day = 60 wallclock minutes
      time_step: "0:00:01" # 1 second * time scale factor
      set_offset: True
      time_status_step: "0:00:10" # 10 seconds * time scale factor
      time_status_init: "2019-03-01T23:59:59+00:00"
      shut_down_when_terminated: True
      manager_app_name: "manager"
    simulator:
      time_scale_factor: 24 # 1 simulation day = 60 wallclock minutes
      time_step: "0:01:00" # 1 second * time scale factor
      set_offset: True
      time_status_step: "0:00:10" # 10 seconds * time scale factor
      time_status_init: "2019-03-01T23:59:59+00:00"
      shut_down_when_terminated: True
      manager_app_name: "manager"
```

# Proposed Changes

## `schemas.py`
- Update the PyDantic model to allow for multiple managed applications to be configured using a dictionary.
- If a field is not provided, use default values specified in ManagedApplicationConfig.

## `application.py` and `managed_application.py`
- Update the `start_up()` method to filter the necessary fields within the dictionary.
- Ensure that only the execution parameters for the specific application (e.g., "planner") are pulled and applied.
